version: '3'

services:

    mongodb:
        build:
            context: ./docker/db
            dockerfile: Dockerfile.mongodb
            args:
                - mongodb_username=${MONGODB_USERNAME}
                - mongodb_password=${MONGODB_PASSWORD}
                - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
        volumes:
            - ./.data/mongo:/data/db:rw
        env_file:
            - .env
        ports:
            - "27017:27017"
    
    mysql:
        build:
            context: ./docker/db
            dockerfile: Dockerfile.mysql
        volumes:
            - ./.data/mysql:/var/lib/mysql:rw
        env_file:
            - .env
        ports:
            - "3306:3306"
    
    postgresql:
        build:
            context: ./docker/db
            dockerfile: Dockerfile.postgresql
        volumes:
            - ./.data/postgresql:/var/lib/postgresql/data:rw
        env_file:
            - .env
        ports:
            - "5432:5432"
